import type {
  ProgrammaticAeoFlags,
  ProgrammaticPatternFamily,
  ProgrammaticUniqueData,
} from '@/lib/graph/types';

export interface PatternCatalogEntry {
  family: ProgrammaticPatternFamily;
  patternName: string;
  exampleTemplate: string;
  buyerMoment: string;
  baseBuyerIntent: number;
  baseAiCitation: number;
  baseUniqueness: number;
  baseThinRisk: number;
  aeoFlags: ProgrammaticAeoFlags;
  uniqueData: ProgrammaticUniqueData;
  risksIfBad: string;
  expectedBenefit: string;
}

export const PATTERN_CATALOG: PatternCatalogEntry[] = [
  {
    family: 'profiles',
    patternName: 'Audience-specific product pages',
    exampleTemplate: '[Product] for [ICP]',
    buyerMoment: 'Evaluation',
    baseBuyerIntent: 85,
    baseAiCitation: 75,
    baseUniqueness: 70,
    baseThinRisk: 45,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: true,
      improvesCitationReadiness: true,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'ICP-specific pain, outcomes, and proof — not a renamed product page',
      realDataNeeded: 'Per-ICP problems, messaging, objections, and relevant case examples',
      proofNeeded: 'One proof asset that matches that audience',
      doNotTemplate: 'Do not swap only the ICP name on identical copy',
    },
    risksIfBad: 'Thin audience clones hurt trust and rankings',
    expectedBenefit: 'Clearer buyer match and conversion paths per ICP',
  },
  {
    family: 'comparisons',
    patternName: 'Comparison pages',
    exampleTemplate: '[Product] vs [Competitor]',
    buyerMoment: 'Comparison',
    baseBuyerIntent: 90,
    baseAiCitation: 88,
    baseUniqueness: 75,
    baseThinRisk: 50,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: true,
      improvesCitationReadiness: true,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'Honest criteria table with real feature/pricing deltas',
      realDataNeeded: 'Competitor names from evidence, differentiation points, migration notes',
      proofNeeded: 'Outcome proof when choosing this product',
      doNotTemplate: 'Do not invent competitor features or fake scorecards',
    },
    risksIfBad: 'Inaccurate comparisons create legal and trust risk',
    expectedBenefit: 'Capture late-stage demand and clarify differentiation',
  },
  {
    family: 'comparisons',
    patternName: 'Alternatives pages',
    exampleTemplate: '[Product] alternatives',
    buyerMoment: 'Consideration',
    baseBuyerIntent: 80,
    baseAiCitation: 82,
    baseUniqueness: 65,
    baseThinRisk: 55,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: true,
      improvesCitationReadiness: true,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'Candid shortlist with when to choose each option',
      realDataNeeded: 'Real alternative names from crawl/intake/query evidence',
      proofNeeded: 'When this product wins vs when it does not',
      doNotTemplate: 'Do not list invented alternatives',
    },
    risksIfBad: 'Generic alternatives lists get ignored by buyers and AI',
    expectedBenefit: 'Own category consideration queries',
  },
  {
    family: 'integrations',
    patternName: 'Integration pages',
    exampleTemplate: '[Product] + [Tool] integration',
    buyerMoment: 'Evaluation',
    baseBuyerIntent: 75,
    baseAiCitation: 70,
    baseUniqueness: 80,
    baseThinRisk: 40,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: true,
      improvesCitationReadiness: false,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'Real setup flow, auth, and use cases per tool',
      realDataNeeded: 'Supported tools, screenshots, setup steps',
      proofNeeded: 'Customer using that integration',
      doNotTemplate: 'Do not publish pages for unsupported tools',
    },
    risksIfBad: 'Fake integrations destroy credibility',
    expectedBenefit: 'Long-tail acquisition and partner SEO',
  },
  {
    family: 'use_case',
    patternName: 'Use case / workflow pages',
    exampleTemplate: '[Use case] / [Workflow]',
    buyerMoment: 'Problem recognition',
    baseBuyerIntent: 82,
    baseAiCitation: 78,
    baseUniqueness: 70,
    baseThinRisk: 45,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: true,
      improvesCitationReadiness: true,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'Concrete workflow steps tied to this offer',
      realDataNeeded: 'Use-case steps, inputs/outputs, buyer moment',
      proofNeeded: 'Example outcome or case study',
      doNotTemplate: 'Do not invent use cases not grounded in intake/crawl',
    },
    risksIfBad: 'Vague use-case pages add crawl bloat without demand',
    expectedBenefit: 'Map demand to concrete buyer paths',
  },
  {
    family: 'examples',
    patternName: 'Examples pages',
    exampleTemplate: '[Use case] examples',
    buyerMoment: 'Evaluation',
    baseBuyerIntent: 78,
    baseAiCitation: 80,
    baseUniqueness: 75,
    baseThinRisk: 50,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: false,
      improvesCitationReadiness: true,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'Real examples with context, not stock scenarios',
      realDataNeeded: 'Named examples from customers, demos, or documented workflows',
      proofNeeded: 'Screenshots or measurable outcomes',
      doNotTemplate: 'Do not fabricate example stories',
    },
    risksIfBad: 'Fake examples get called out and hurt AEO trust',
    expectedBenefit: 'Improve proof density across buyer paths',
  },
  {
    family: 'glossary',
    patternName: 'Glossary / definition pages',
    exampleTemplate: 'What is [category term]',
    buyerMoment: 'Awareness',
    baseBuyerIntent: 55,
    baseAiCitation: 92,
    baseUniqueness: 60,
    baseThinRisk: 60,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: true,
      improvesCitationReadiness: true,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'Operator-accurate definition tied to this product entity',
      realDataNeeded: 'Term, who it is for, related offer, FAQ objections',
      proofNeeded: 'Light example or proof',
      doNotTemplate: 'Do not mass-publish synonym spam pages',
    },
    risksIfBad: 'Thin glossary farms dilute authority',
    expectedBenefit: 'Improve AI answerability and entity clarity',
  },
  {
    family: 'templates',
    patternName: 'Template / generator pages',
    exampleTemplate: '[Workflow] template',
    buyerMoment: 'Consideration',
    baseBuyerIntent: 70,
    baseAiCitation: 65,
    baseUniqueness: 55,
    baseThinRisk: 70,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: false,
      improvesCitationReadiness: false,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'Downloadable or usable artifact specific to this offer',
      realDataNeeded: 'Template fields, example filled version, CTA to product',
      proofNeeded: 'Usage proof if available',
      doNotTemplate: 'Do not ship empty placeholder templates',
    },
    risksIfBad: 'Low-value templates look spammy and raise thin-content risk',
    expectedBenefit: 'Capture mid-funnel demand with lead magnets',
  },
  {
    family: 'converters',
    patternName: 'Converter / calculator pages',
    exampleTemplate: '[Metric] calculator / converter',
    buyerMoment: 'Evaluation',
    baseBuyerIntent: 72,
    baseAiCitation: 60,
    baseUniqueness: 65,
    baseThinRisk: 55,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: false,
      improvesCitationReadiness: false,
      improvesAiOverview: false,
    },
    uniqueData: {
      whatMakesUnique: 'Working logic with assumptions disclosed',
      realDataNeeded: 'Formulas, inputs, industry defaults from real ops knowledge',
      proofNeeded: 'Optional case using the calculator output',
      doNotTemplate: 'Do not publish broken or misleading calculators',
    },
    risksIfBad: 'Wrong math destroys trust',
    expectedBenefit: 'High-intent engagement before CTA',
  },
  {
    family: 'directories',
    patternName: 'Category directory pages',
    exampleTemplate: '[Category] directory',
    buyerMoment: 'Awareness',
    baseBuyerIntent: 50,
    baseAiCitation: 55,
    baseUniqueness: 80,
    baseThinRisk: 75,
    aeoFlags: {
      improvesAnswerability: false,
      improvesEntityClarity: true,
      improvesCitationReadiness: false,
      improvesAiOverview: false,
    },
    uniqueData: {
      whatMakesUnique: 'Curated entries with editorial criteria',
      realDataNeeded: 'Real listings, filters, inclusion rules',
      proofNeeded: 'Why each entry qualifies',
      doNotTemplate: 'Do not auto-generate empty directory shells',
    },
    risksIfBad: 'Doorway directories invite quality penalties',
    expectedBenefit: 'Hub for related programmatic children',
  },
  {
    family: 'curation',
    patternName: 'Curated list pages',
    exampleTemplate: 'Best [category] for [ICP]',
    buyerMoment: 'Consideration',
    baseBuyerIntent: 75,
    baseAiCitation: 70,
    baseUniqueness: 75,
    baseThinRisk: 65,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: false,
      improvesCitationReadiness: true,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'Transparent ranking criteria and original picks',
      realDataNeeded: 'Criteria, scored items from real research',
      proofNeeded: 'Why winners earned inclusion',
      doNotTemplate: 'Do not republish generic “top 10” spam',
    },
    risksIfBad: 'Affiliate-style fluff without criteria fails AEO and trust',
    expectedBenefit: 'Capture listicle demand with editorial authority',
  },
  {
    family: 'locations',
    patternName: 'Location / service-area pages',
    exampleTemplate: '[Service] in [Location]',
    buyerMoment: 'Local evaluation',
    baseBuyerIntent: 80,
    baseAiCitation: 50,
    baseUniqueness: 85,
    baseThinRisk: 70,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: false,
      improvesCitationReadiness: false,
      improvesAiOverview: false,
    },
    uniqueData: {
      whatMakesUnique: 'Local proof, coverage, and contact specifics',
      realDataNeeded: 'Cities/regions you actually serve; local proof',
      proofNeeded: 'Local customers or case notes',
      doNotTemplate: 'Do not mass-create cities you do not serve',
    },
    risksIfBad: 'Fake local pages are a classic spam pattern',
    expectedBenefit: 'Win local intent where the business operates',
  },
  {
    family: 'localization',
    patternName: 'Localized language pages',
    exampleTemplate: '[Offer] in [Language/Market]',
    buyerMoment: 'Evaluation',
    baseBuyerIntent: 65,
    baseAiCitation: 55,
    baseUniqueness: 80,
    baseThinRisk: 60,
    aeoFlags: {
      improvesAnswerability: true,
      improvesEntityClarity: true,
      improvesCitationReadiness: false,
      improvesAiOverview: true,
    },
    uniqueData: {
      whatMakesUnique: 'Native language messaging and market proof',
      realDataNeeded: 'Target markets, translated offers, local CTAs',
      proofNeeded: 'Market-specific customers if available',
      doNotTemplate: 'Do not machine-translate without review',
    },
    risksIfBad: 'Poor localization looks unprofessional',
    expectedBenefit: 'Expand into markets with real demand',
  },
];
